import { CXAI_ASSISTANT_FEATURE } from "../feature-name";

export enum CxaiAssistantOutlets {
  START_BUTTON = `${CXAI_ASSISTANT_FEATURE}.START_BUTTON`,
  CHAT_BUTTONS = `${CXAI_ASSISTANT_FEATURE}.CHAT_BUTTONS`,
  TITLEBAR_ACTIONS = `${CXAI_ASSISTANT_FEATURE}.TITLEBAR_ACTIONS`,
}

